"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var filter_1 = require("./filter");
exports.BloomFilter = filter_1.default;
var buffer_backend_1 = require("./buffer-backend");
exports.BufferBackend = buffer_backend_1.makeWithSize;
var dummy_hasher_1 = require("./dummy-hasher");
exports.DummyHasher = dummy_hasher_1.default;
var params_1 = require("./params");
exports.getOptimalParams = params_1.getOptimalParams;
